/**
 * Parts 页面双语数据源（由元件注册表生成，勿手改；改表后重跑 generate-parts-data.js）
 *
 * 来源：白名单检测-基因片段列表.xlsx（本队元件注册表）
 * 说明：
 * - 序列已清洗（去空白/换行/大写）；HA 蛋白序列原含每 50bp 位置编号，已剥离还原为 1698 bp
 * - 表中未提供 iGEM Registry 编号，故不生成 BBa 号，只保留「是否在库 / 是否送检」状态
 * - 骨架（无序列载体）与抗体试剂单独分组，不计入元件数
 */

module.exports = {
  overview: {
    totalParts: 18,
    groupCount: 3,
    backboneCount: 6,
    reagentCount: 2,
    intro: {
      zh: '本页列出 PAGER-Yeast 项目中使用的全部生物元件，按信号识别、信号转导优化、信号报告三个功能模块归置。每个元件给出编号、名称与描述，长序列可展开查看。',
      en: 'This page lists every biological part used in PAGER-Yeast, grouped into three functional modules: signal recognition, signal transduction optimisation, and signal reporter. Each part carries its identifier, name and description, with long sequences available to expand.'
    },
    note: {
      zh: '元件编号将在完成登记后填入，届时每一条目左侧的编号即指向 Registry 页面。',
      en: 'Part identifiers are filled in once registration is complete; each identifier on the left then links to its Registry page.'
    }
  },
  groups: [
    {
      id: "signal-recognition",
      zh: "信号识别模块",
      en: "Signal Recognition Module",
      desc: { zh: "负责识别甲型流感病毒 HA 抗原，由信号肽、抑制域、纳米抗体、酶切位点与受体依次串成。", en: "Recognises the influenza A HA antigen; built from a signal peptide, an inhibitory domain, a nanobody, a cleavage site and a receptor joined in sequence." },
      parts: [
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "α-factor 信号肽（SP）",
          en: "α-factor signal peptide (SP)",
          fn: {
            zh: "信号肽。引导融合蛋白进入分泌途径并锚定在酵母细胞膜上。",
            en: "Signal peptide. Guides the fusion protein into the secretory pathway and anchors it on the yeast plasma membrane."
          },
          length: 57,
          seq: "ATGAGATTTCCTTCTATTTTTACTGCTGTTTTGTTTGCTGCTTCTTCTGCTTTAGCA"
        },
        // ⚠ 核验：Registry 库内未见同类元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "MT1（毒蕈碱毒素 1）C 端截短片段",
          en: "MT1 (muscarinic toxin 1), C-terminally truncated fragment",
          fn: {
            zh: "抑制域。自抑制开关，无抗原时结合并抑制 hM1Dq。",
            en: "Inhibitory domain. Self-inhibition switch that binds and blocks hM1Dq when no antigen is present."
          },
          length: 186,
          seq: "TTGACTTGTGTTACTTCTAAATCAATTTTTGGTATTACTACTGAAAATTGTCCTGATGGTCAAAATTTGTGTTTTAAAAAATGGTATTATATAGTTCCTAGATATTCTGATATAACATGGGGTTGTGCAGCTACTTGTCCTAAACCAACTAATGTTAGAGAAACTATTAGATGTTGTGAAACAGAT"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "H1N1 HA 纳米抗体 R1a-B6（结合茎部）",
          en: "H1N1 HA nanobody R1a-B6 (stem-binding)",
          fn: {
            zh: "纳米抗体。特异性结合甲型流感病毒 HA 茎部，是整条链路的核心识别单元。",
            en: "Nanobody. Binds the influenza A HA stem specifically; the core recognition unit of the whole cascade."
          },
          length: 342,
          seq: "CAAGTTCAATTAGTTGAATCTGGTGGTGGTTTAGTTCAACCAGGTGGTTCTTTAAGATTATCATGTGCTGCTTCAGGTTCATTTTTCTCTAGATATAGGATGGGTTGGTACAGACAAGCTCCTGGTGAACAAAGAGAATTAGTTGCTTCAATTGCTTATGATGGTTCTACATCATACGCTGATCCTGTTAAAGGTAGATTCACTATTTCTAGAGATAATGCAAATACAGTTCATTTGCAAATGTATTCTTTAAAACCAGATGATACAGCTGTTTATTACTGTAACTTGGACCCACCTGGTATTTTGTATTGGGGTCAAGGTACTCAAGTGACAGTTAGTAGT"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "TEV 蛋白酶切位点（TEVcs）",
          en: "TEV protease cleavage site (TEVcs)",
          fn: {
            zh: "蛋白酶切位点。体外功能验证用的分子开关，可模拟抗原解锁。",
            en: "Protease cleavage site. Molecular switch for in-vitro verification, used to mimic antigen unlocking."
          },
          length: 21,
          seq: "GAAAATTTGTACTTTCAATCA"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "hM1Dq（人源 M1 DREADD 受体）",
          en: "hM1Dq (human M1 DREADD receptor)",
          fn: {
            zh: "受体。接收上游信号并偶联下游 G 蛋白通路，可被 DCZ 激活。",
            en: "Receptor. Receives the upstream signal and couples to the downstream G-protein pathway; activated by DCZ."
          },
          length: 1380,
          seq: "ATGAATACTAGTGCTCCTCCTGCAGTATCTCCTAATATAACAGTTTTAGCACCAGGCAAGGGTCCATGGCAAGTTGCTTTTATTGGTATTACTACTGGTTTACTTAGCTTAGCTACTGTTACAGGTAATTTGTTAGTTTTAATTAGTTTTAAAGTTAACACTGAACTTAAAACTGTTAATAATTACTTTTTACTAAGTTTAGCTTGTGCTGATTTGATAATTGGTACTTTTTCTATGAACTTATACACAACTTACTTATTAATGGGTCATTGGGCTTTAGGTACTTTAGCTTGTGATCTTTGGTTAGCTTTAGATTGTGTTGCTTCTAATGCATCTGTTATGAATTTGCTATTAATTTCCTTTGATAGATATTTTTCCGTAACTAGGCCTTTAAGTTATAGAGCTAAAAGAACTCCTAGGAGAGCTGCTTTAATGATTGGTTTAGCATGGTTAGTTTCTTTTGTCTTGTGGGCTCCAGCAATTTTATTTTGGCAATATCTGGTTGGTGAAAGAACTGTTTTAGCTGGTCAATGTTATATTCAATTTTTATCACAACCAATAATTACATTTGGAACAGCTATGGCTGGTTTTTATCTTCCTGTTACTGTTATGTGTACTTTATATTGGAGAATATATAGAGAAACAGAAAATAGAGCTAGAGAATTAGCTGCTTTACAAGGTAGTGAAACTCCAGGTAAAGGTGGTGGTAGTTCTTCATCTTCTGAAAGATCTCAACCAGGTGCTGAAGGTTCTCCTGAAACACCACCAGGTAGATGTTGTAGATGTTGTAGAGCTCCAAGATTATTGCAAGCTTACTCATGGAAAGAAGAAGAAGAGGAAGATGAAGGTTCTATGGAATCATTAACATCATCTGAAGGTGAAGAACCAGGTTCTGAAGTTGTTATTAAGATGCCAATGGTTGATCCTGAAGCTCAAGCTCCAACTAAACAACCACCTAGGTCCTCTCCAAACACTGTTAAAAGACCAACTAAAAAAGGTAGAGATAGAGCTGGTAAAGGTCAAAAACCTAGGGGTAAAGAACAATTAGCTAAAAGAAAAACTTTTTCATTAGTTAAAGAAAAGAAAGCTGCTAGAACTTTGAGTGCTATTTTATTAGCTTTTATTCTAACTTGGACACCATATAATATAATGGTTTTAGTTTCTACATTTTGTAAAGATTGTGTTCCTGAAACTCTTTGGGAATTAGGTTACTGGTTATGTTATGTTAATAGTACTATTAATCCAATGTGTTATGCATTGTGTAATAAGGCTTTTAGAGATACTTTTAGATTATTGTTATTATGTAGATGGGATAAAAGAAGATGGAGAAAAATTCCAAAAAGACCTGGTTCTGTTCATAGAACTCCTAGTAGACAATGT"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "HA 蛋白（甲型流感病毒血凝素）",
          en: "HA protein (influenza A hemagglutinin)",
          fn: {
            zh: "抗原。本项目的检测目标，用于功能测试中的抗原刺激。",
            en: "Antigen. The detection target of this project, used for antigen stimulation in functional assays."
          },
          length: 1698,
          seq: "ATGAAGGCCATCCTGGTGGTGATGCTGTACACCTTCACCACCGCCAACGCCGACACCCTGTGCATCGGCTACCACGCCAACAACAGCACCGACACCGTGGACACCGTGCTGGAGAAGAACGTGACCGTGACCCACAGCGTGAACCTGCTGGAGGACAAGCACAACGGCAAGCTGTGCAAGCTGCGCGGCGTGGCCCCCCTGCACCTGGGCCAGTGCAACATCGCCGGCTGGATCCTGGGCAACCCCGAGTGCGAGAGCCTGAGCACCGCCCGCAGCTGGAGCTACATCGTGGAGACCAGCAACAGCGACAACGGCACCTGCTACCCCGGCGACTTCATCAACTACGAGGAGCTGCGCGAGCAGCTGAGCAGCGTGAGCAGCTTCGAGCGCTTCGAGATCTTCCCCAAGACCAGCAGCTGGCCCAACCACGACAGCGACAACGGCGTGACCGCCGCCTGCAGCCACGCCGGCGCCCGCAGCTTCTACAAGAACCTGATCTGGCTGGTGAAGAAGGGCAAGAGCTACCCCAAGATCAACCAGACCTACATCAACGACAAGGGCAAGGAGGTGCTGGTGCTGTGGGGCATCCACCACCCCCCCACCATCACCGACCAGGAGAGCCTGTACCAGAACGCCGACGCCTACGTGTTCGTGGGCACCAGCCGCTACAGCAAGAAGTTCAAGCCCGAGATCGCCGCCCGCCCCAAGGTGCGCGACCAGGCCGGCCGCATGAACTACTACTGGACCCTGGTGGAGCCCGGCGACAAGATCACCTTCGAGGCCACCGGCAACCTGGTGGCCCCCCGCTACGCCTTCACCATGGAGAAGGAGGCCGGCAGCGGCATCATCATCAGCGACACCCCCGTGCACGACTGCAACGCCACCTGCCAGACCCCCGAGGGCGCCATCAACACCAGCCTGCCCTTCCAGAACGTGCACCCCATCACCATCGGCAAGTGCCCCAAGTACGTGCGCAGCACCAAGCTGCGCCTGGCCACCGGCCTGCGCAACGTGCCCAGCATCCAGAGCCGCGGCCTGTTCGGCGCCATCGCCGGCTTCATCGAGGGCGGCTGGACCGGCATGGTGGACGGCTGGTACGGCTACCACCACCAGAACGACCAGGGCAGCGGCTACGCCGCCGACCTGAAGAGCACCCAGAACGCCATCGACAAGATCACCAACAAGGTGAACAGCGTGATCGAGAAGATGAACACCCAGTTCACCGCCGTGGGCAAGGAGTTCAACCACCTGGAGAAGCGCATCGAGAACCTGAACAAGAAGGTGGACGACGGCTTCCTGGACGTGTGGACCTACAACGCCGAGCTGCTGGTGCTGCTGGAGAACGAGCGCACCCTGGACTACCACGACAGCAACGTGAAGAACCTGTACGAGAAGGTGCGCCACCAGCTGAAGAACAACGCCAAGGAGATCGGCAACGGCTGCTTCGAGTTCTACCACAAGTGCGACAACACCTGCATGGAGAGCGTGAAGAACGGCACCTACGACTACCCCAAGTACAGCGAGGAGGCCAAGCTGAACCGCGAGAAGATCGACGGCGTGAAGCTGGACAGCACCCGCATCTACCAGATCCTGGCCATCTACAGCACCGTGGCCAGCAGCCTGGTGCTGGTGGTGAGCCTGGGCGCCATCAGCTTCTGGATGTGCAGCAACGGCAGCCTGCAGTGCCGCATCTGCATC"
        }
      ]
    },
    {
      id: "signal-transduction",
      zh: "信号转导优化模块",
      en: "Signal Transduction Optimization Module",
      desc: { zh: "负责降低背景、释放生长、放大信号，包含三基因敲除元件与 Gpa1 人源化改造片段。", en: "Cuts background, releases growth and amplifies the signal; holds the three-gene knockout elements and the Gpa1 humanisation fragment." },
      parts: [
        // ⚠ 核验：Registry 待登记 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "URA3（含启动子与终止子）",
          en: "URA3 (with promoter and terminator)",
          fn: {
            zh: "筛选标记。尿嘧啶营养筛选标记，在 SD-Ura 平板上筛选阳性整合克隆。",
            en: "Selection marker. Uracil selection marker for picking positive integrants on SD-Ura plates."
          },
          length: 1240,
          seq: "TTCAATTCAATTCATCATTTTTTTTTTATTCTTTTTTTTGATTTCGGTTTCTTTGAAATTTTTTTGATTCGGTAATCTCCGAACAGAAGGAAGAACGAAGGAAGGAGCACAGACTTAGATTGGTATATATACGCATATGTAGTGTTGAAGAAACATGAAATTGCCCAGTATTCTTAACCCAACTGCACAGAACAAAAACCTGCAGGAAACGAAGATAAATCATGTCGAAAGCTACATATAAGGAACGTGCTGCTACTCATCCTAGTCCTGTTGCTGCCAAGCTATTTAATATCATGCACGAAAAGCAAACAAACTTGTGTGCTTCATTGGATGTTCGTACCACCAAGGAATTACTGGAGTTAGTTGAAGCATTAGGTCCCAAAATTTGTTTACTAAAAACACATGTGGATATCTTGACTGATTTTTCCATGGAGGGCACAGTTAAGCCGCTAAAGGCATTATCCGCCAAGTACAATTTTTTACTCTTCGAAGACAGAAAATTTGCTGACATTGGTAATACAGTCAAATTGCAGTACTCTGCGGGTGTATACAGAATAGCAGAATGGGCAGACATTACGAATGCACACGGTGTGGTGGGCCCAGGTATTGTTAGCGGTTTGAAGCAGGCGGCAGAAGAAGTAACAAAGGAACCTAGAGGCCTTTTGATGTTAGCAGAATTGTCATGCAAGGGCTCCCTATCTACTGGAGAATATACTAAGGGTACTGTTGACATTGCGAAGAGCGACAAAGATTTTGTTATCGGCTTTATTGCTCAAAGAGACATGGGTGGAAGAGATGAAGGTTACGATTGGTTGATTATGACACCCGGTGTGGGTTTAGATGACAAGGGAGACGCATTGGGTCAACAGTATAGAACCGTGGATGATGTGGTCTCTACAGGATCTGACATTATTATTGTTGGAAGAGGACTATTTGCAAAGGGAAGGGATGCTAAGGTAGAGGGTGAACGTTACAGAAAAGCAGGCTGGGAAGCATATTTGAGAAGATGCGGCCAGCAAAACTAAAAAACTGTATTATAAGTAAATGCATGTATACTAAACTCACAAATTAGAGCTTCAATTTAATTATATCAGTTATTACCCTATGCGGTGTGAAATACCGCACAGATGCGTAAGGAGAAAATACCGCATCAGGAAATTGTAAACGTTAATATTTTGTTAAAATTCGCGTTAAATTTTTGTTAAATCAGCTCATTTTTTAACCAATAGGCCGAAATCGG"
        },
        // ⚠ 核验：Registry 待登记 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "GPA1 改造位点前 500 bp 上游同源臂",
          en: "500 bp upstream homology arm at the GPA1 edit site",
          fn: {
            zh: "同源臂。同源重组整合片段的上游臂，用于定点替换 Gpa1 C 端。",
            en: "Homology arm. Upstream arm of the integration fragment, used for site-directed replacement of the Gpa1 C-terminus."
          },
          length: 500,
          seq: "ACAGGCATTACAGAAACCGAATTTAACATCGGCTCGTCCAAATTCAAGGTTCTCGACGCTGGTGGGCAGCGTTCTGAACGTAAGAAGTGGATTCATTGTTTCGAAGGAATTACAGCAGTTTTATTTGTTTTAGCAATGAGTGAATACGACCAGATGTTGTTTGAGGATGAAAGAGTGAACAGAATGCATGAATCAATAATGCTATTTGACACGTTATTGAACTCTAAGTGGTTCAAAGATACACCGTTTATTTTGTTTTTAAATAAAATTGATTTGTTCGAGGAAAAGGTAAAAAGCATGCCCATAAGAAAGTACTTTCCTGATTACCAGGGACGTGTCGGCGATGCAGAAGCGGGTCTAAAATATTTTGAGAAGATATTTTTGAGCTTGAATAAGACAAACAAACCAATCTACGTGAAACGAACCTGCGCTACCGATACCCAAACTATGAAGTTCGTATTGAGTGCAGTCACCGATCTAATCATCCAGCAAAACCTTAA"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "人源化替换序列（EYNLV + 终止密码子）",
          en: "Humanised replacement sequence (EYNLV + stop codon)",
          fn: {
            zh: "改造位点。把 Gpa1 C 端 KIGII 换成 EYNLV，使 hM1Dq 能与酵母 MAPK 通路偶联。",
            en: "Edit site. Replaces the Gpa1 C-terminal KIGII with EYNLV so hM1Dq can couple to the yeast MAPK pathway."
          },
          length: 18,
          seq: "GAATATAATTTGGTTTGA"
        },
        // ⚠ 核验：Registry 待登记 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "GPA1 改造位点后 500 bp 下游同源臂",
          en: "500 bp downstream homology arm at the GPA1 edit site",
          fn: {
            zh: "同源臂。同源重组整合片段的下游臂，与上游臂共同界定替换区间。",
            en: "Homology arm. Downstream arm of the integration fragment; together with the upstream arm it defines the replaced region."
          },
          length: 500,
          seq: "AGGAACTGTATAATTAAAGTAGTGTTTAGATACGTAAATTCTGTTTCCGAAGATGCAAGAAGGAGCAGCAGCACCAGAAAAAATTACTATTTTTCTTCTCCATTAGAGTCTATGATGGAATGCCAAATGAAAAAGCCATTTTGTTCAACAGTTCTTGATCTCGTTAAATCGTTCCGGGTTTTCAATTGAAAAACAAGGGTAATAAAATCGCATGAGAAAAAAAAGGTCCAGACACTTTTTTAGAAGAAAAACTCTTGAAAACAATTGATTCTTCTACGTAAGGACAGGGTATTATCTCGAATTCTTCTCCCTGGTAAATACTCGGGATATATAGAACCTATTTTGCATCCTATTCTCACTTTTCTTTATTGTTGTTAATTTCTGGACATTGTTTCATTAATTGAATGAATGCCCTAAAATATTTCTCAAATCATTTAATAACTACAAAGAAACAAAAAAAAATCAATGTTGAGGTGACAAAGAATCAAGATCTACTAGGC"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "SpCas9（来自 pML104）",
          en: "SpCas9 (from pML104)",
          fn: {
            zh: "核酸酶。CRISPR 编辑用核酸酶，由 sgRNA 引导在靶位点产生双链断裂。",
            en: "Nuclease. CRISPR nuclease guided by the sgRNA to create a double-strand break at the target site."
          },
          length: 1719,
          seq: "ATGGACAAGAAGTATTCTATCGGACTGGACATCGGGACTAATAGCGTCGGGTGGGCCGTCATCACTGACGAGTACAAGGTGCCCTCTAAGAAGTTCAAGGTGCTCGGGAACACCGACCGGCATTCCATCAAGAAAAATCTGATCGGAGCTCTCCTCTTTGATTCAGGGGAGACCGCTGAAGCAACCCGCCTCAAGCGGACTGCTAGACGGCGGTACACCAGGAGGAAGAACCGGATTTGTTACCTTCAAGAGATATTCTCCAACGAAATGGCAAAGGTCGACGACAGCTTCTTCCATAGGCTGGAAGAATCATTCCTCGTGGAAGAGGATAAGAAGCATGAACGGCATCCCATCTTCGGTAATATCGTCGACGAGGTGGCCTATCACGAGAAATACCCAACCATCTACCATCTTCGCAAAAAGCTGGTGGACTCAACCGACAAGGCAGACCTCCGGCTTATCTACCTGGCCCTGGCCCACATGATTAAGTTCAGAGGCCACTTCCTGATCGAGGGCGACCTCAATCCTGACAATAGCGATGTGGATAAACTGTTCATCCAGCTGGTGCAGACTTACAACCAGCTCTTTGAAGAGAACCCCATCAATGCAAGCGGAGTCGATGCCAAGGCCATTCTGTCAGCCCGGCTGTCAAAGAGCCGCAGACTTGAGAATCTTATCGCTCAGCTGCCGGGTGAAAAGAAAAATGGACTGTTCGGGAACCTGATTGCTCTTTCACTTGGGCTGACTCCCAATTTCAAGTCTAATTTCGACCTGGCAGAGGATGCCAAGCTGCAACTGTCCAAGGACACCTATGATGACGATCTCGACAACCTCCTGGCCCAGATCGGTGACCAATACGCCGACCTTTTCCTTGCTGCTAAGAATCTTTCTGACGCCATCCTGCTGTCTGACATTCTCCGCGTGAACACTGAAATCACCAAGGCCCCTCTTTCAGCTTCAATGATTAAGCGGTATGATGAGCACCACCAGGACCTGACCCTGCTTAAGGCACTCGTCCGGCAGCAGCTTCCGGAGAAGTACAAGGAAATCTTCTTTGACCAGTCAAAGAATGGATACGCCGGCTACATCGACGGAGGTGCCTCCCAAGAGGAATTTTATAAGTTTATCAAACCTATCCTTGAGAAGATGGACGGCACCGAAGAGCTCCTCGTGAAACTGAATCGGGAGGATCTGCTGCGGAAGCAGCGCACTTTCGACAATGGGAGCATTCCCCACCAGATCCATCTTGGGGAGCTTCACGCCATCCTTCGGCGCCAAGAGGACTTCTACCCCTTTCTTAAGGACAACAGGGAGAAGATTGAGAAAATTCTCACTTTCCGCATCCCCTACTACGTGGGACCCCTCGCCAGAGGAAATAGCCGGTTTGCTTGGATGACCAGAAAGTCAGAAGAAACTATCACTCCCTGGAACTTCGAAGAGGTGGTGGACAAGGGAGCCAGCGCTCAGTCATTCATCGAACGGATGACTAACTTCGATAAGAACCTCCCCAATGAGAAGGTCCTGCCGAAACATTCCCTGCTCTACGAGTACTTTACCGTGTACAACGAGCTGACCAAGGTGAAATATGTCACCGAAGGGATGAGGAAGCCCGCATTCCTGTCAGGCGAACAAAAGAAGGCAATTGTGGACCTTCTGTTCAAGACCAATAGAAAGGTGACCGTGAAGCAGCTGAAGGAGGACTATTTCAAGAAAATTGAA"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "sgRNA（FAR1）",
          en: "sgRNA (FAR1)",
          fn: {
            zh: "向导 RNA。引导 SpCas9 切割 FAR1 位点，实现该基因敲除。",
            en: "Guide RNA. Guides SpCas9 to cut the FAR1 locus for knockout of that gene."
          },
          length: 89,
          seq: "GCAGTGAAAGATAAATGATCACCAAGTTTGAAGAAAACAGGTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAA"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "sgRNA（STE2）",
          en: "sgRNA (STE2)",
          fn: {
            zh: "向导 RNA。引导 SpCas9 切割 STE2 位点，实现该基因敲除。",
            en: "Guide RNA. Guides SpCas9 to cut the STE2 locus for knockout of that gene."
          },
          length: 89,
          seq: "GCAGTGAAAGATAAATGATCTCACCTCTACTGATGAACTGGTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAA"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "sgRNA（Sst2）",
          en: "sgRNA (Sst2)",
          fn: {
            zh: "向导 RNA。引导 SpCas9 切割 Sst2 位点，实现该基因敲除。",
            en: "Guide RNA. Guides SpCas9 to cut the Sst2 locus for knockout of that gene."
          },
          length: 89,
          seq: "GCAGTGAAAGATAAATGATCACACCGCAGGACAGAACTCGGTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAA"
        }
      ]
    },
    {
      id: "signal-reporter",
      zh: "信号报告模块",
      en: "Signal Reporter Module",
      desc: { zh: "把通路激活转成可读出信号，含启动子与荧光、显色两类报告基因。", en: "Turns pathway activation into a readable signal; holds the promoter plus fluorescent and colourimetric reporters." },
      parts: [
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "yEGFP（酵母优化型绿色荧光蛋白）",
          en: "yEGFP (yeast-optimised enhanced GFP)",
          fn: {
            zh: "报告基因。绿色荧光报告基因，用流式细胞术做定量读数。",
            en: "Reporter. Green fluorescent reporter read out quantitatively by flow cytometry."
          },
          length: 729,
          seq: "GAATTCATGTCTAAAGGTGAAGAATTATTCACTGGTGTTGTCCCAATTTTGGTTGAATTAGATGGTGATGTTAATGGTCACAAATTTTCTGTCTCCGGTGAAGGTGAAGGTGATGCTACTTACGGTAAATTGACCTTAAAATTTATTTGTACTACTGGTAAATTGCCAGTTCCATGGCCAACCTTAGTCACTACTTTCGGTTATGGTGTTCAATGTTTTGCTAGATACCCAGATCATATGAAACAACATGACTTTTTCAAGTCTGCCATGCCAGAAGGTTATGTTCAAGAAAGAACTATTTTTTTCAAAGATGACGGTAACTACAAGACCAGAGCTGAAGTCAAGTTTGAAGGTGATACCTTAGTTAATAGAATCGAATTAAAAGGTATTGATTTTAAAGAAGATGGTAACATTTTAGGTCACAAATTGGAATACAACTATAACTCTCACAATGTTTACATCATGGCTGACAAACAAAAGAATGGTATCAAAGTTAACTTCAAAATTAGACACAACATTGAAGATGGTTCTGTTCAATTAGCTGACCATTATCAACAAAATACTCCAATTGGTGATGGTCCAGTCTTGTTACCAGACAACCATTACTTATCCACTCAATCTGCCTTATCCAAAGATCCAAACGAAAAGAGAGACCACATGGTCTTGTTAGAATTTGTTACTGCTGCTGGTATTACCCATGGTATGGATGAATTGTACAAATAAGGATCC"
        },
        // ⚠ 核验：Registry 库内已有相似元件 · 送检 已送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "FUS1 启动子",
          en: "FUS1 promoter",
          fn: {
            zh: "启动子。G 蛋白响应启动子，通路激活后启动下游报告基因转录。",
            en: "Promoter. G-protein-responsive promoter that drives reporter transcription once the pathway is activated."
          },
          length: 435,
          seq: "ACGATGATTCAGTTCGCCTTCTATCCTTTGTTTACGTATTTGTTTATATATATAACTTTATTTTTTTTTATTAATTGGGCTGCAAGACAATTTTGTTGTCAGTGATGCCTCAATCCTTCTTTTGCTTCCATATTTACCATGTGGACCCTTTCAAAACAGAGTTGTATCTCTGCAGGATGCCCTTTTTGACGTATTGAATGGCATAATTGCACTGTCACTTTTCGCGCTGTCTCATTTTGGTGCGATGATGAAACAAACATGAAACGTCTGTAATTTGAAACAAATAACGTAATTCTCGGGATTGGTTTTATTTAAATGACAATGTAAGAGTGGCTTTGTAAGGTATGTGTTGCTCTTAAAATATTTGGATACGACATCCTTTATCTTTTTTCCTTTAAGAGCAGGATATAAGCCATCAAGTTTCTGAAAATCAAA"
        },
        // ⚠ 核验：Registry 待登记 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "MEL1（α-半乳糖苷酶）",
          en: "MEL1 (alpha-galactosidase)",
          fn: {
            zh: "报告基因。分泌型报告基因，用于报告输出的备选读出方式。",
            en: "Reporter. Secreted reporter kept as an alternative readout for the output stage."
          },
          length: 1416,
          seq: "ATGTTTGCTTTCTACTTTCTCACCGCATGCATCAGTTTGAAGGGCGTTTTTGGGGTGTCTCCGAGTTACAATGGCCTTGGTCTCACTCCACAGATGGGTTGGGACAACTGGAATACGTTTGCCTGCGATGTCAGTGAACAGCTACTTCTAGACACCGCTGATAGAATTTCTGACTTGGGGCTAAAGGATATGGGTTACAAGTATATCATTCTGGATGACTGCTGGTCTAGCGGCAGAGATTCCGACGGTTTCCTCGTTGCAGATGAACAAAAATTTCCCAATGGTATGGGCCATGTTGCAGACCACCTGCATAATAACAGCTTTCTTTTCGGTATGTATTCGTCTGCTGGTGAGTACACCTGTGCTGGATATCCTGGGTCTCTGGGTCGTGAGGAAGAAGATGCACAGTTCTTTGCAAATAACCGCGTTGACTACTTGAAGTACGATAATTGTTACAATAAGGGTCAGTTTGGTACACCGGAAATTTCTTACCACCGTTACAAGGCCATGTCAGATGCTTTGAATAAAACTGGTAGGCCTATATTCTATTCTCTATGTAACTGGGGTCAGGATTTAACATTTTACTGGGGCTCTGGTATCGCCAATTCTTGGAGAATGAGTGGAGATGTTACTGCTGAGTTCACTCGTCCAGATAGCAGATGTCCCTGTGATGGCGATGAATACGATTGCAAGTACGCCGGTTTCCATTGTTCTATTATGAATATTCTTAACAAGGCAGCTCCAATGGGGCAAAATGCAGGTGTTGGTGGTTGGAATGATCTGGACAATCTAGAGGTTGGTGTCGGGAATTTGACTGACGATGAGGAAAAGGCACATTTCTCTATGTGGGCAATGGTAAAGTCTCCACTTATCATTGGTGCCAATGTGAATAACTTAAAGGCATCTTCGTACTCAATCTATAGTCAAGCCTCTGTCATCGCAATTAATCAAGATTCAAATGGTATTCCAGCAACAAGAGTCTGGAGATATTATGTTTCAGACACAGATGAATATGGACAAGGTGAAATTCAAATGTGGAGTGGTCCTCTTGACAATGGTGATCAAGTGGTTGCTTTATTGAATGGAGGAAGCGTATCTAGACCAATGAACACGACCTTGGAAGAGATTTTTTTTGACAGCAATCTGGGTTCAAAGAAACTGACATCGACTTGGGATATCTACGACCTATGGGCCAACAGAGTTGACAACTCGACAGCGTCTGCTATCCTTGGACGGAATAAGACAGCCACCGGTATTCTCTACAATGCTACGGAGCAATCCTACAAAGACGGTTTGTCTAAGAATGATACAAGACTGTTTGGTCAGAAAATTGGTAGTCTTTCTCCAAATGCTATACTTAACACGACTGTTCCAGCTCACGGTATCGCCTTCTATAGGTTGAGACCCTCTTCTTGA"
        },
        // ⚠ 核验：Registry 待登记 · 送检 待送检
        {
          id: null, // ⚠ 核验：元件 ID 待分配，登记后填入编号与链接
          zh: "LACZα（含多克隆位点）",
          en: "LACZα (with multiple cloning site)",
          fn: {
            zh: "报告基因。β-半乳糖苷酶 α 片段，带多克隆位点，可用 X-Gal 显色判读。",
            en: "Reporter. β-galactosidase α fragment carrying a multiple cloning site; read out by X-Gal staining."
          },
          length: 315,
          seq: "ATGTTGCATCATCATCATCATCATAGCATGCATATGCTGCAGCTCGAGTCGACGGATCCGAATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACTTAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGCCTGATGCGGTATTTTCTCCTTACGCATCTGTGCGGTATTTCACACCGTATATGGTGCACTCTCAGTACAATCTGCTCTGATGCCGCATAG"
        }
      ]
    }
  ],
  backbones: [
    {
      zh: "pGADT7（ZB56914）",
      en: "pGADT7 (ZB56914)",
      fn: { zh: "PAGER 融合蛋白基因的克隆骨架。", en: "Cloning backbone for the PAGER fusion protein gene." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    },
    {
      zh: "PUC57",
      en: "PUC57",
      fn: { zh: "基因合成片段的递送载体。", en: "Delivery vector for the synthesised gene fragment." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    },
    {
      zh: "pRS426",
      en: "pRS426",
      fn: { zh: "酵母用附加体型载体。", en: "Yeast episomal vector." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    },
    {
      zh: "pML104",
      en: "pML104",
      fn: { zh: "CRISPR-Cas9 酵母敲除质粒，表达 Cas9 与 sgRNA。", en: "CRISPR-Cas9 yeast knockout plasmid, expressing Cas9 and the sgRNA." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    },
    {
      zh: "pESC-HIS",
      en: "pESC-HIS",
      fn: { zh: "酵母报告骨架，承载 FUS1 报告盒。", en: "Yeast reporter backbone carrying the FUS1 reporter cassette." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    },
    {
      zh: "pRS415",
      en: "pRS415",
      fn: { zh: "酵母用着丝粒型载体。", en: "Yeast centromeric vector." },
      // ⚠ 核验：Registry 待登记 · 送检 待送检
    }
  ],
  reagents: [
  {
    "zh": "山羊抗兔 IgG H&L（HRP 标记）",
    "en": "Goat anti-rabbit IgG H&L (HRP)",
    "fn": {
      "zh": "Western blot 二抗。",
      "en": "Secondary antibody for Western blot."
    }
  },
  {
    "zh": "CoraLite® Plus 488 标记 6×His 单克隆抗体",
    "en": "CoraLite® Plus 488-conjugated 6×His, His-Tag monoclonal antibody",
    "fn": {
      "zh": "免疫荧光用一抗，检测带 His 标签的融合蛋白。",
      "en": "Primary antibody for immunofluorescence, detecting His-tagged fusion protein."
    }
  }
]
};
